data :
  name : "mnist"
  path : "data/datasets/mnist_examples.pth"
  x : "data/datasets/mnist_examples.pth"
  y : 2
  ytarget : 3
  num_classes : 10
  num_samples : 1000
  num_channels : 1
  bounds_method : "alpha-CROWN"
  L : 
  - -5
  - -50
  - -50
  - -1000.0
  U :
  - 5.0
  - 15.0
  - 100.0
  - 1000.0

epsilon : 0.01

network :
  name : "MLP-ADV"
  path : "data/models/mnist_adv_MLP-ADV.pt"
  K : 4
  n : 
    - 784
    - 200
    - 100
    - 50
    - 10
  # name : "9x100"
  # path : "data/models/mnist_adv_9x100.pt"
  # K : 10
  # n : 
  #   - 784
  #   - 100
  #   - 100
  #   - 100
  #   - 100
  #   - 100
  #   - 100
  #   - 100
  #   - 100
  #   - 100
  #   - 10

models :
  - certification_model_name : "LanSDP"
    cuts : 
    - "RLT"
    - "triangularization"
    RLT_prop : 0.2
    all_combinations_cuts : false
    MATRIX_BY_LAYERS: true
    LAST_LAYER: false
    use_fusion: false  # Whether to use the fusion API for MOSEK
    use_active_neurons: false # Whether to use active neurons in the certification problem as variables
    use_inactive_neurons : false # Whether to use inactive neurons in the certification problem as variables
