data : "concatmnist-20-classes"
train_path  : "data/datasets/MNIST/ConcatMNIST/20_classes/balanced_emnist_fashion_kmnist_train.pth"
test_path   : "data/datasets/MNIST/ConcatMNIST/20_classes/balanced_emnist_fashion_kmnist_test.pth"
evaluate_robustness_path : "data/datasets/MNIST/ConcatMNIST/20_classes/concatmnist_subset_1_per_class.pth"
num_classes : 20
# Projected Gradient Descent (PGD)
adversarial_attack : "PGD"
epsilon : 0.3
epsilon_test : 0.010
alpha : 0.01
steps : 40
random_start : true
num_epochs : 100
lr : 0.001
batch_size : 128
n :
  - 784
  - 100
  - 100
  - 100
  - 100
  - 100
  - 100
  - 20
K : 7
name_network : "concatmnist-6x100-20-classes"


  